<a href="https://colab.research.google.com/github/Rajendar98/pyTorch_Learning/blob/main/pyTorch_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

In [4]:
# Tensor manipulating
# Addition
# Subtraction
# Multiplication
# Matrix Multiplication

In [5]:
a=torch.tensor([1,2,3])
print(a)
print( a + 10 )
print(torch.add(a,10))

tensor([1, 2, 3])
tensor([11, 12, 13])
tensor([11, 12, 13])


In [6]:
print( a * 10)
print(torch.mul(a,10))

tensor([10, 20, 30])
tensor([10, 20, 30])


In [7]:
print( a - 10 )
print(torch.sub(a,10))

tensor([-9, -8, -7])
tensor([-9, -8, -7])


In [8]:
b=torch.tensor([4,5,6])
print(b)

tensor([4, 5, 6])


In [9]:
matrixmul=torch.matmul(a,b) # use matmul or @ give same output
print( a @ b )
print(a,"*",b)
print(matrixmul)

tensor(32)
tensor([1, 2, 3]) * tensor([4, 5, 6])
tensor(32)


In [10]:
# The 2 main rules  that performing matrix multiplication need to staisfy
# (2,3) @ (2,3) --> won't work
# (2,3) @ (3,2) -->(2,3) will work because the inner dimensions are equal
# (3,2) @ (2,3) -->(3,3) will work

In [11]:
a=torch.tensor([[1,2],[3,4],[5,6]])
b=torch.tensor([[1,2,3],[4,5,6]])
r=torch.matmul(a,b)
print(r)

tensor([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])


In [12]:
# The transpose matrix use (.T)

In [13]:
print("Transpose matrix\n",r.T)

Transpose matrix
 tensor([[ 9, 19, 29],
        [12, 26, 40],
        [15, 33, 51]])


In [14]:
# Finding the min,max,mean,sum etc.......

In [15]:
x=torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [16]:
print(torch.max(x))
print(torch.min(x))

tensor(91)
tensor(1)


In [17]:
torch.sum(x)

tensor(460)

In [18]:
# NOTE;-
# The torch.mean() function requires a tensor of float32 datatype to work
print(torch.mean(x.type(torch.float32)))
print(x.type(torch.float32).mean())

tensor(46.)
tensor(46.)


In [19]:
# find the minimum and maximum element position in tensor
print(x.argmin())
print(x.argmax())

tensor(0)
tensor(9)


In [20]:
# Reshaping, Stacking ,Squeezing ,UnSqueezing tensors and permute

In [25]:
x=torch.arange(1.,10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
print(x.reshape(3,3))
print(x.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.Size([9])


In [33]:
print(x.view(1,9))
print(x.view(3,3))
print(x.shape)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.Size([9])


In [38]:
z=x.view(1,9)
print(z[:,0])

tensor([1.])


In [41]:
print(torch.stack([x,x,x,x],dim=0))
print()
print(torch.stack([x,x,x,x],dim=1))

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])


In [45]:
x_reshape=x.reshape(1,9)
print(x_reshape)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])


In [48]:
t=x_reshape.squeeze()
print(t)
print(x_reshape.squeeze().shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.Size([9])


In [47]:
x_reshape

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [56]:
print(x_reshape)
print(x_reshape.shape)
print(x_reshape.unsqueeze(dim=0))
print(x_reshape.unsqueeze(dim=0).shape)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) 

torch.Size([1, 9])
tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])
torch.Size([1, 1, 9])


In [58]:
a=torch.rand(224,224,3)
a_permute=a.permute(2,0,1)
print(a.shape)
print(a_permute.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


In [80]:
#Indexing with pytorch
b=torch.arange(1,10).reshape(1,3,3)
print(b,end="-->")
print(b.shape)
print(b[0])
print(b[0][2])
print(b[0][2][2])
print(b[0,0,:])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])-->torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([7, 8, 9])
tensor(9)
tensor([1, 2, 3])


In [ ]:
# Pytorch tensors and NumPy

In [81]:
import numpy as np

In [85]:
array=np.arange(1.0,8.0)
tens=torch.from_numpy(array)
print(tens.type(dtype=torch.float32))
print(array)
print(tens)

tensor([1., 2., 3., 4., 5., 6., 7.])
[1. 2. 3. 4. 5. 6. 7.]
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [86]:
array=array+1
print(array)
print(tens)

[2. 3. 4. 5. 6. 7. 8.]
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [90]:
f=torch.ones(7)
np_tensor=f.numpy()
print(f)
np_tensor

tensor([1., 1., 1., 1., 1., 1., 1.])


array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [91]:
f=f+1
print(f)
print(np_tensor)

tensor([2., 2., 2., 2., 2., 2., 2.])
[1. 1. 1. 1. 1. 1. 1.]


In [93]:
rand_A=torch.rand(1,9).reshape(1,3,3)
rand_B=torch.rand(1,9).reshape(1,3,3)
print(rand_A)
print(rand_B)
print(rand_A==rand_B)

tensor([[[0.1185, 0.2991, 0.6701],
         [0.4818, 0.9821, 0.6725],
         [0.2644, 0.2206, 0.0787]]])
tensor([[[0.2021, 0.9735, 0.2371],
         [0.6365, 0.5808, 0.1095],
         [0.5860, 0.0633, 0.4114]]])
tensor([[[False, False, False],
         [False, False, False],
         [False, False, False]]])


In [100]:
RANDOM_SEED = 6  #random seed is reproducibility
torch.manual_seed(RANDOM_SEED)
rand_C=torch.rand(1,9).reshape(1,3,3)
torch.manual_seed(RANDOM_SEED)
rand_D=torch.rand(1,9).reshape(1,3,3)
print(rand_C)
print(rand_D)
print(rand_C==rand_D)

tensor([[[0.5722, 0.5539, 0.9868],
         [0.6080, 0.2347, 0.4492],
         [0.6743, 0.7480, 0.5601]]])
tensor([[[0.5722, 0.5539, 0.9868],
         [0.6080, 0.2347, 0.4492],
         [0.6743, 0.7480, 0.5601]]])
tensor([[[True, True, True],
         [True, True, True],
         [True, True, True]]])


In [107]:
torch.cuda.is_available()

False

In [108]:
x=torch.tensor([1,2,3]) # Create a tensor the default device is  CPU
print(x.device)

cpu


In [ ]:
# Top three error in deep learning
# 1--> Shape errors
# 2--> Data type Issues
# 3--> Device Issues

In [114]:
torch.cuda.is_available()

False