In [ ]:
import torch

In [ ]:
#creating a tensors
temp=torch.tensor(6)
temp

tensor(6)

In [ ]:
temp.ndim #ndim-->Dimension

0

In [ ]:
temp.item()

6

In [ ]:
vect=torch.tensor([6,6]) #Vector creation

In [ ]:
vect.ndim

1

In [ ]:
vect.shape

torch.Size([2])

In [ ]:
vect.size()

torch.Size([2])

In [ ]:
#Matrix Creation
mat=torch.tensor([[1,2],[3,4],[4,6]])
mat

tensor([[1, 2],
        [3, 4],
        [4, 6]])

In [ ]:
print(mat[0],mat[1])

tensor([1, 2]) tensor([3, 4])


In [ ]:
print(mat.shape)
mat.size()

torch.Size([3, 2])


torch.Size([3, 2])

In [ ]:
ten=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(ten)
print(ten.shape)
print(ten[0])
print(ten[0][1])
print(ten[0][1][2])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([4, 5, 6])
tensor(6)


In [ ]:
### Random Tensors
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8659, 0.8136, 0.6999, 0.2242],
        [0.5684, 0.6855, 0.0049, 0.2507],
        [0.7168, 0.5423, 0.1218, 0.9518]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_image_size_tensor=torch.rand(size=(3,224,224)) #size=(1-> color channel(Red,green,Blue),
print(random_image_size_tensor.shape)                 #      2-> height,
print(random_image_size_tensor.ndim)                  #      3-> width)

torch.Size([3, 224, 224])
3


In [ ]:
# Creating tensor of all Zeros and ones
zeros=torch.zeros(3,4)
print(zeros)
ones=torch.ones(3,4)
print()
print(ones)
print(zeros.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


In [ ]:
# Creating a range of tensors and tensors-like
x=torch.arange(0,21,2) #Start , end ,Step
print(x)
print(x.ndim)
print(x.shape)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])
1
torch.Size([11])


In [ ]:
ten_ones=torch.ones_like(x)
ten_zeros=torch.zeros_like(x)
print(ten_zeros)
print(ten_ones)
print(ten_zeros.dtype)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
torch.int64


In [ ]:
# Tensor Datatypes
# Tensor attributes-->{(tensor.shape or tensor.size()),tensor.device,tensor.dtype}
a=torch.tensor([1.2,2.3,1.0,2.6],
               dtype=None,
               device=None,
               requires_grad=False)
print(a.dtype)
b=a.type(torch.float16) #Conversion flot32 --> float 16
print(b.dtype)
print(a*b)
print(a.device)
print(a.shape)

torch.float32
torch.float16
tensor([1.4402, 5.2918, 1.0000, 6.7590])
cpu
torch.Size([4])
